### ISSUE TITLE
redirect old BEP pages to their relevant page in the mkdocs.yml

### ISSUE THREAD

**Issue by Remi-Gau** [bids-standard/bids-website#403]
## why ?

when the new site will replace the old one some URL will die ☠️. So better put some redirect in place.

## TODO

- [x] delete the _bep-collection folder in the bfm branch: https://github.com/bids-standard/bids-website/tree/bfm/_bep_collection
- [x] update the mkdocs in the main branch with redirects for each old page to point to where the BEP lives

see redirects section here: https://github.com/bids-standard/bids-website/blob/2ce099db576d8edd41f6730bedf87b8b635a6a07/mkdocs.yml#L22

an example below

```yml
  - redirects:
      redirect_maps:
        "bep004": "https://docs.google.com/document/d/1kyw9mGgacNqeMbp4xZet3RnDhcMmf4_BmRgKaOkO2Sc/"
```

I do not think we will keep those redirect forever but at least it will prevent some confusion after we roll out the new website.
